# Generated by Django 4.0 on 2022-02-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='source',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
