# Generated by Django 4.0 on 2022-03-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_alter_expenditure_amount_alter_source_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='date_deposited',
        ),
        migrations.RemoveField(
            model_name='source',
            name='created_at',
        ),
    ]
