# Generated by Django 4.0 on 2022-06-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_rent_ternants'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='ternant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='contributions.ternants'),
            preserve_default=False,
        ),
    ]
