# Generated by Django 4.0 on 2022-04-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_delete_balance_remove_expenditure_date_deposited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='status',
        ),
        migrations.RemoveField(
            model_name='source',
            name='status',
        ),
    ]
